const USER_ACTION_TYPES = {
    USER_AUTHENTICATE_START: 'USER_AUTHENTICATE_START',
    USER_AUTHENTICATE_SUCCESS: 'USER_AUTHENTICATE_SUCCESS',
    USER_AUTHENTICATE_FAIL: 'USER_AUTHENTICATE_FAIL',

    CHECK_USER_SESSION_START: 'CHECK_USER_SESSION_START',
    CHECK_USER_SESSION_SUCCESS: 'CHECK_USER_SESSION_SUCCESS',
    CHECK_USER_SESSION_FAIL: 'CHECK_USER_SESSION_FAIL',

    GET_USER_ADDRESS_START: 'GET_USER_ADDRESS_START',
    GET_USER_ADDRESS_SUCCESS: 'GET_USER_ADDRESS_SUCCESS',
};

export default USER_ACTION_TYPES;