const  PRODUCT_ACTION_TYPES = {
    GET_TOP_PRODUCTS_START: 'GET_TOP_PRODUCTS_START',
    GET_TOP_PRODUCTS_SUCCESS: 'GET_TOP_PRODUCTS_SUCCESS',
    GET_TOP_PRODUCTS_FAIL: 'GET_TOP_PRODUCTS_FAIL',

    GET_SINGLE_PRODUCT_START: 'GET_SINGLE_PRODUCT_START',
    GET_SINGLE_PRODUCT_SUCCESS: 'GET_SINGLE_PRODUCT_SUCCESS',
    GET_SINGLE_PRODUCT_FAIL: 'GET_SINGLE_PRODUCT_FAIL',

    GET_PRODUCT_CATEGORIES_START: 'GET_PRODUCT_CATEGORIES_START',
    GET_PRODUCT_CATEGORIES: 'GET_PRODUCT_CATEGORIES',

    GET_CITIES_START: 'GET_CITIES_START',
    GET_CITIES_LIST: 'GET_CITIES_LIST',

    SET_ORDERED_PRODUCT_START: 'SET_ORDERED_PRODUCT_START',
    SET_ORDERED_PRODUCT_SUCCESS: 'SET_ORDERED_PRODUCT_SUCCESS',
    SET_ORDERED_PRODUCT_FAIL: 'SET_ORDERED_PRODUCT_FAIL',

    GET_NEW_PRODUCTS_START: 'GET_NEW_PRODUCTS_START',
    GET_NEW_PRODUCTS_SUCCESS: 'GET_NEW_PRODUCTS_SUCCESS',

    GET_DISCOUNTED_PRODUCTS_START: 'GET_DISCOUNTED_PRODUCTS_START',
    GET_DISCOUNTED_PRODUCTS_SUCCESS: 'GET_DISCOUNTED_PRODUCTS_SUCCESS',

    GET_ORDERED_PRODUCTS_START: 'GET_ORDERED_PRODUCTS_START',
    GET_ORDERED_PRODUCTS_SUCCESS: 'GET_ORDERED_PRODUCTS_SUCCESS',
}

export default PRODUCT_ACTION_TYPES;